// <auto-generated />
using System;
using Matterway.Catalog.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matterway.Catalog.Api.Migrations
{
    [DbContext(typeof(CatalogDb))]
    partial class CatalogDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DomainProduct", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            CreatedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The Philips Hue White and Color Ambiance A19 Smart LED Bulb lets you control your lights from your smartphone or tablet. Choose from 16 million colors to match the mood of any room, and set the lights to turn on and off on a schedule or when you're away from home.",
                            IsAvailable = true,
                            Price = 4999.0,
                            ProductCode = "PH-002",
                            Title = "Philips Hue White and Color Ambiance A19 Smart LED Bulb",
                            UpdatedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            CreatedAt = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "The 3rd generation Nest Learning Thermostat programs itself and automatically saves energy when you're away. It learns what temperature you like and builds a schedule around yours.",
                            IsAvailable = true,
                            Price = 24999.0,
                            ProductCode = "NT-003",
                            Title = "Nest Learning Thermostat",
                            UpdatedAt = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            CreatedAt = new DateTime(2024, 6, 3, 16, 45, 0, 0, DateTimeKind.Utc),
                            Description = "The August Wi-Fi Smart Lock Pro + Connect lets you add secure keyless entry to your home. Lock and unlock your door with your phone, and give keyless entry to family, friends, housekeepers, and other home services without worrying about lost or copied keys.",
                            IsAvailable = true,
                            Price = 27999.0,
                            ProductCode = "AL-001",
                            Title = "August Wi-Fi Smart Lock Pro",
                            UpdatedAt = new DateTime(2024, 6, 3, 16, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            CreatedAt = new DateTime(2024, 6, 4, 11, 15, 0, 0, DateTimeKind.Utc),
                            Description = "The Amazon Echo (4th Gen) is a hands-free smart speaker that you control with your voice. It connects to Alexa to play music, make calls, set alarms and timers, ask questions, control smart home devices, and more.",
                            IsAvailable = true,
                            Price = 9999.0,
                            ProductCode = "AE-004",
                            Title = "Amazon Echo (4th Gen)",
                            UpdatedAt = new DateTime(2024, 6, 4, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            CreatedAt = new DateTime(2024, 6, 5, 13, 20, 0, 0, DateTimeKind.Utc),
                            Description = "The Ring Spotlight Cam is a wireless security camera that lets you see, hear, and speak to anyone on your property from your phone, tablet, or PC. It has built-in spotlights and a siren to deter intruders, and it works with Alexa to let you control it with your voice.",
                            IsAvailable = true,
                            Price = 19999.0,
                            ProductCode = "RS-001",
                            Title = "Ring Spotlight Cam",
                            UpdatedAt = new DateTime(2024, 6, 5, 13, 20, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.ProductDetail", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ProductId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("DomainProductDetail", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            TypeId = 7,
                            Value = "Works with Alexa, Google Assistant, and Apple HomeKit"
                        },
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            TypeId = 12,
                            Value = "24-bit color LCD, 480 x 480 resolution at 229 pixels per inch (PPI)"
                        },
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            TypeId = 8,
                            Value = "Requires 24VAC power, uses less than 1 kWh/month"
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            TypeId = 11,
                            Value = "Wi-Fi and Bluetooth"
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            TypeId = 10,
                            Value = "Works with Alexa, Google Assistant, and Siri"
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            TypeId = 9,
                            Value = "Uses four AA batteries (included), lasts up to 6 months depending on usage"
                        },
                        new
                        {
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            TypeId = 13,
                            Value = "Adjustable from warm white (2700K) to daylight (6500K)"
                        },
                        new
                        {
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            TypeId = 10,
                            Value = "Works with Alexa, Google Assistant, and Samsung SmartThings"
                        },
                        new
                        {
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            TypeId = 8,
                            Value = "9"
                        },
                        new
                        {
                            ProductId = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            TypeId = 4,
                            Value = "970"
                        },
                        new
                        {
                            ProductId = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            TypeId = 7,
                            Value = "Wi-Fi and Bluetooth"
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            TypeId = 14,
                            Value = "1080p HD"
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            TypeId = 15,
                            Value = "Two-way audio with noise cancellation"
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            TypeId = 11,
                            Value = "Wi-Fi and Ethernet"
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.ProductDetailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("DomainProductDetailType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Width",
                            Unit = "millimeters"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Height",
                            Unit = "millimeters"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Depth",
                            Unit = "millimeters"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Weight",
                            Unit = "grams"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Color"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Material"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Connectivity"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Power",
                            Unit = "Watts"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Battery"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Compatibility"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Connectivity"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Display"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Color Temperature",
                            Unit = "Kelvin"
                        },
                        new
                        {
                            Id = 14,
                            Title = "Video Quality"
                        },
                        new
                        {
                            Id = 15,
                            Title = "Audio Quality"
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id", "ProductId");

                    b.HasIndex("ProductId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("DomainProductImage", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9dc0c1db-a949-4cb8-8a8c-2f55de2f1f90"),
                            ProductId = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            ImageAlt = "Amazon Echo Show 5",
                            ImageUrl = "https://m.media-amazon.com/images/I/51iobpaEM5S._AC_SL1000_.jpg",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = new Guid("05ffe3d2-d56d-4fd2-b816-7b1ef82b1e62"),
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            ImageAlt = "Spotlight Cam Plus",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/2393/8647/products/ring_spotlight_cam_plus_insitu_battery_1500x1500_0a5ecca0-fa41-49d7-86ad-01d797694845.jpg",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = new Guid("72cebb50-7f20-4c2a-9803-ccc9934274be"),
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            ImageAlt = "Philips Hue White and Color Ambiance A19 Smart LED Bulb - Front View",
                            ImageUrl = "https://images.homedepot-static.com/productImages/7d8edcf4-11b5-4cf1-8747-7ba637f618d1/svn/philips-led-bulbs-464487-64_1000.jpg",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = new Guid("55ab96f9-8b3b-42b0-a933-643522cd7397"),
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            ImageAlt = "Nest Learning Thermostat - Front View",
                            ImageUrl = "https://i.pinimg.com/originals/95/99/16/959916d70bd67c4a5a3d160078b7f266.jpg",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = new Guid("88423aa2-93bb-462c-9934-7e783e680b98"),
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            ImageAlt = "August Wi-Fi Smart Lock Pro - Front View",
                            ImageUrl = "https://images.homedepot-static.com/productImages/e2f3a648-f053-4e00-92fb-4349a0f344a2/svn/august-electronic-deadbolts-augsl05-m01-s01-64_1000.jpg",
                            OrderIndex = 0
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.ProductDetail", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matterway.Catalog.Api.Domain.ProductDetailType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.ProductImage", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Product", b =>
                {
                    b.Navigation("ProductDetails");

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
