// <auto-generated />
using System;
using Matterway.Catalog.Api.Providers.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matterway.Catalog.Api.Migrations
{
    [DbContext(typeof(CatalogDbComposer))]
    partial class CatalogDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.AttributeSlug", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Slug");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("AttributeSlug", (string)null);

                    b.HasData(
                        new
                        {
                            Slug = "audio"
                        },
                        new
                        {
                            Slug = "audio-quality"
                        },
                        new
                        {
                            Slug = "battery"
                        },
                        new
                        {
                            Slug = "brand"
                        },
                        new
                        {
                            Slug = "camera"
                        },
                        new
                        {
                            Slug = "color"
                        },
                        new
                        {
                            Slug = "color-temperature"
                        },
                        new
                        {
                            Slug = "compatibility"
                        },
                        new
                        {
                            Slug = "connectivity"
                        },
                        new
                        {
                            Slug = "display"
                        },
                        new
                        {
                            Slug = "features"
                        },
                        new
                        {
                            Slug = "material"
                        },
                        new
                        {
                            Slug = "model"
                        },
                        new
                        {
                            Slug = "operating-system"
                        },
                        new
                        {
                            Slug = "ports"
                        },
                        new
                        {
                            Slug = "processor"
                        },
                        new
                        {
                            Slug = "resolution"
                        },
                        new
                        {
                            Slug = "video-quality"
                        },
                        new
                        {
                            Slug = "battery-size"
                        },
                        new
                        {
                            Slug = "depth"
                        },
                        new
                        {
                            Slug = "height"
                        },
                        new
                        {
                            Slug = "power"
                        },
                        new
                        {
                            Slug = "ram-size"
                        },
                        new
                        {
                            Slug = "refresh-rate"
                        },
                        new
                        {
                            Slug = "screen-size"
                        },
                        new
                        {
                            Slug = "storage"
                        },
                        new
                        {
                            Slug = "weight"
                        },
                        new
                        {
                            Slug = "width"
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Detail", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Slug");

                    b.ToTable("Detail", (string)null);

                    b.HasData(
                        new
                        {
                            Slug = "audio",
                            Title = "Audio"
                        },
                        new
                        {
                            Slug = "audio-quality",
                            Title = "Audio Quality"
                        },
                        new
                        {
                            Slug = "battery",
                            Title = "Battery"
                        },
                        new
                        {
                            Slug = "brand",
                            Title = "Brand"
                        },
                        new
                        {
                            Slug = "camera",
                            Title = "Camera"
                        },
                        new
                        {
                            Slug = "color",
                            Title = "Color"
                        },
                        new
                        {
                            Slug = "color-temperature",
                            Title = "Color Temperature"
                        },
                        new
                        {
                            Slug = "compatibility",
                            Title = "Compatibility"
                        },
                        new
                        {
                            Slug = "connectivity",
                            Title = "Connectivity"
                        },
                        new
                        {
                            Slug = "display",
                            Title = "Display"
                        },
                        new
                        {
                            Slug = "features",
                            Title = "Features"
                        },
                        new
                        {
                            Slug = "material",
                            Title = "Material"
                        },
                        new
                        {
                            Slug = "model",
                            Title = "Model"
                        },
                        new
                        {
                            Slug = "operating-system",
                            Title = "Operating System"
                        },
                        new
                        {
                            Slug = "ports",
                            Title = "Ports"
                        },
                        new
                        {
                            Slug = "processor",
                            Title = "Processor"
                        },
                        new
                        {
                            Slug = "resolution",
                            Title = "Resolution"
                        },
                        new
                        {
                            Slug = "video-quality",
                            Title = "Video Quality"
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Discount", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code", "ProductId", "Currency");

                    b.HasIndex("ProductId", "Currency");

                    b.ToTable("Discount", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "WINTER25",
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            Currency = "RSD",
                            Percentage = 0.25m,
                            ValidFrom = new DateTime(2025, 11, 19, 23, 0, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2026, 3, 19, 23, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Price", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId", "Currency");

                    b.ToTable("Price", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            Currency = "RSD",
                            Amount = 4999m
                        },
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            Currency = "RSD",
                            Amount = 24999m
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            Currency = "RSD",
                            Amount = 27999m
                        },
                        new
                        {
                            ProductId = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            Currency = "RSD",
                            Amount = 9999m
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            Currency = "RSD",
                            Amount = 19999m
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            CreatedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The Philips Hue White and Color Ambiance A19 Smart LED Bulb lets you control your lights from your smartphone or tablet. Choose from 16 million colors to match the mood of any room, and set the lights to turn on and off on a schedule or when you're away from home.",
                            IsAvailable = true,
                            ProductCode = "PH002",
                            Title = "Philips Hue White and Color Ambiance A19 Smart LED Bulb",
                            UpdatedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            CreatedAt = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "The 3rd generation Nest Learning Thermostat programs itself and automatically saves energy when you're away. It learns what temperature you like and builds a schedule around yours.",
                            IsAvailable = true,
                            ProductCode = "NT003",
                            Title = "Nest Learning Thermostat",
                            UpdatedAt = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            CreatedAt = new DateTime(2024, 6, 3, 16, 45, 0, 0, DateTimeKind.Utc),
                            Description = "The August Wi-Fi Smart Lock Pro + Connect lets you add secure keyless entry to your home. Lock and unlock your door with your phone, and give keyless entry to family, friends, housekeepers, and other home services without worrying about lost or copied keys.",
                            IsAvailable = true,
                            ProductCode = "AL001",
                            Title = "August Wi-Fi Smart Lock Pro",
                            UpdatedAt = new DateTime(2024, 6, 3, 16, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            CreatedAt = new DateTime(2024, 6, 4, 11, 15, 0, 0, DateTimeKind.Utc),
                            Description = "The Amazon Echo (4th Gen) is a hands-free smart speaker that you control with your voice. It connects to Alexa to play music, make calls, set alarms and timers, ask questions, control smart home devices, and more.",
                            IsAvailable = true,
                            ProductCode = "AE004",
                            Title = "Amazon Echo (4th Gen)",
                            UpdatedAt = new DateTime(2024, 6, 4, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            CreatedAt = new DateTime(2024, 6, 5, 13, 20, 0, 0, DateTimeKind.Utc),
                            Description = "The Ring Spotlight Cam is a wireless security camera that lets you see, hear, and speak to anyone on your property from your phone, tablet, or PC. It has built-in spotlights and a siren to deter intruders, and it works with Alexa to let you control it with your voice.",
                            IsAvailable = true,
                            ProductCode = "RS001",
                            Title = "Ring Spotlight Cam",
                            UpdatedAt = new DateTime(2024, 6, 5, 13, 20, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ProductDetail", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailSlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ProductId", "DetailSlug");

                    b.HasIndex("DetailSlug");

                    b.ToTable("ProductDetail", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            DetailSlug = "compatibility",
                            Value = "Works with Alexa, Google Assistant, and Apple HomeKit"
                        },
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            DetailSlug = "display",
                            Value = "24-bit color LCD, 480 x 480 resolution at 229 pixels per inch (PPI)"
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            DetailSlug = "connectivity",
                            Value = "Wi-Fi and Bluetooth"
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            DetailSlug = "compatibility",
                            Value = "Works with Alexa, Google Assistant, and Siri"
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            DetailSlug = "battery",
                            Value = "Uses four AA batteries (included), lasts up to 6 months depending on usage"
                        },
                        new
                        {
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            DetailSlug = "color-temperature",
                            Value = "Adjustable from warm white (2700K) to daylight (6500K)"
                        },
                        new
                        {
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            DetailSlug = "compatibility",
                            Value = "Works with Alexa, Google Assistant, and Samsung SmartThings"
                        },
                        new
                        {
                            ProductId = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            DetailSlug = "connectivity",
                            Value = "Wi-Fi and Bluetooth"
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            DetailSlug = "video-quality",
                            Value = "1080p HD"
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            DetailSlug = "audio-quality",
                            Value = "Two-way audio with noise cancellation"
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            DetailSlug = "connectivity",
                            Value = "Wi-Fi and Ethernet"
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id", "ProductId");

                    b.HasIndex("ProductId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("ProductImage", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9dc0c1db-a949-4cb8-8a8c-2f55de2f1f90"),
                            ProductId = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            ImageAlt = "Amazon Echo Show 5",
                            ImageUrl = "https://m.media-amazon.com/images/I/51iobpaEM5S._AC_SL1000_.jpg",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = new Guid("05ffe3d2-d56d-4fd2-b816-7b1ef82b1e62"),
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            ImageAlt = "Spotlight Cam Plus",
                            ImageUrl = "https://images.ctfassets.net/a3peezndovsu/product-24529407541337-media/6eaa58ced96b0dc6959181f55dec6023/product-24529407541337-media.jpg",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = new Guid("72cebb50-7f20-4c2a-9803-ccc9934274be"),
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            ImageAlt = "Philips Hue White and Color Ambiance A19 Smart LED Bulb - Front View",
                            ImageUrl = "https://images.homedepot-static.com/productImages/7d8edcf4-11b5-4cf1-8747-7ba637f618d1/svn/philips-led-bulbs-464487-64_1000.jpg",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = new Guid("55ab96f9-8b3b-42b0-a933-643522cd7397"),
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            ImageAlt = "Nest Learning Thermostat - Front View",
                            ImageUrl = "https://i.pinimg.com/originals/95/99/16/959916d70bd67c4a5a3d160078b7f266.jpg",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = new Guid("88423aa2-93bb-462c-9934-7e783e680b98"),
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            ImageAlt = "August Wi-Fi Smart Lock Pro - Front View",
                            ImageUrl = "https://images.homedepot-static.com/productImages/e2f3a648-f053-4e00-92fb-4349a0f344a2/svn/august-electronic-deadbolts-augsl05-m01-s01-64_1000.jpg",
                            OrderIndex = 0
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ProductSpecification", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecificationSlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ProductId", "SpecificationSlug");

                    b.HasIndex("SpecificationSlug");

                    b.ToTable("ProductSpecification", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            SpecificationSlug = "power",
                            Value = 24m
                        },
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            SpecificationSlug = "width",
                            Value = 84m
                        },
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            SpecificationSlug = "height",
                            Value = 84m
                        },
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            SpecificationSlug = "depth",
                            Value = 28m
                        },
                        new
                        {
                            ProductId = new Guid("8d9d9e68-6d44-49c7-8fcb-a6db28969e5a"),
                            SpecificationSlug = "screen-size",
                            Value = 2.0m
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            SpecificationSlug = "battery-size",
                            Value = 3000m
                        },
                        new
                        {
                            ProductId = new Guid("0d6a9017-47e1-4477-86a9-67d9d9e468b8"),
                            SpecificationSlug = "weight",
                            Value = 400m
                        },
                        new
                        {
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            SpecificationSlug = "power",
                            Value = 9m
                        },
                        new
                        {
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            SpecificationSlug = "weight",
                            Value = 72m
                        },
                        new
                        {
                            ProductId = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            SpecificationSlug = "weight",
                            Value = 970m
                        },
                        new
                        {
                            ProductId = new Guid("20d76c1a-6d4e-4f22-9262-c20dc62f6f2c"),
                            SpecificationSlug = "power",
                            Value = 15m
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            SpecificationSlug = "power",
                            Value = 8m
                        },
                        new
                        {
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            SpecificationSlug = "weight",
                            Value = 480m
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Specification", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Slug");

                    b.ToTable("Specification", (string)null);

                    b.HasData(
                        new
                        {
                            Slug = "battery-size",
                            Title = "Battery Size",
                            Unit = "mAh"
                        },
                        new
                        {
                            Slug = "depth",
                            Title = "Depth",
                            Unit = "millimeters"
                        },
                        new
                        {
                            Slug = "height",
                            Title = "Height",
                            Unit = "millimeters"
                        },
                        new
                        {
                            Slug = "power",
                            Title = "Power",
                            Unit = "watts"
                        },
                        new
                        {
                            Slug = "ram-size",
                            Title = "RAM Size",
                            Unit = "GB"
                        },
                        new
                        {
                            Slug = "refresh-rate",
                            Title = "Refresh Rate",
                            Unit = "Hz"
                        },
                        new
                        {
                            Slug = "screen-size",
                            Title = "Screen Size",
                            Unit = "inches"
                        },
                        new
                        {
                            Slug = "storage",
                            Title = "Storage",
                            Unit = "GB"
                        },
                        new
                        {
                            Slug = "weight",
                            Title = "Weight",
                            Unit = "grams"
                        },
                        new
                        {
                            Slug = "width",
                            Title = "Width",
                            Unit = "millimeters"
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Detail", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.AttributeSlug", null)
                        .WithMany()
                        .HasForeignKey("Slug")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Discount", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Price", "Price")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductId", "Currency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Price", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ProductDetail", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Detail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ProductSpecification", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Product", "Product")
                        .WithMany("ProductSpecifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Specification", "Specification")
                        .WithMany()
                        .HasForeignKey("SpecificationSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Specification");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Specification", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.AttributeSlug", null)
                        .WithMany()
                        .HasForeignKey("Slug")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Price", b =>
                {
                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("ProductDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductSpecifications");
                });
#pragma warning restore 612, 618
        }
    }
}
