// <auto-generated />
using System;
using Matterway.Catalog.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matterway.Catalog.Api.Migrations
{
    [DbContext(typeof(CatalogDbComposer))]
    partial class CatalogDbComposerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Article", b =>
                {
                    b.Property<string>("ArticleCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleCode");

                    b.ToTable("Article", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleCode = "PHUE0002",
                            BasePrice = 4999m,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The Philips Hue White and Color Ambiance A19 Smart LED Bulb lets you control your lights from your smartphone or tablet. Choose from 16 million colors to match the mood of any room, and set the lights to turn on and off on a schedule or when you're away from home.",
                            IsAvailable = true,
                            Title = "Philips Hue White and Color Ambiance A19 Smart LED Bulb",
                            UpdatedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ArticleCode = "NEST0003",
                            BasePrice = 24999m,
                            CreatedAt = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "The 3rd generation Nest Learning Thermostat programs itself and automatically saves energy when you're away. It learns what temperature you like and builds a schedule around yours.",
                            IsAvailable = true,
                            Title = "Nest Learning Thermostat",
                            UpdatedAt = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ArticleCode = "AUGL0001",
                            BasePrice = 27999m,
                            CreatedAt = new DateTime(2024, 6, 3, 16, 45, 0, 0, DateTimeKind.Utc),
                            Description = "The August Wi-Fi Smart Lock Pro + Connect lets you add secure keyless entry to your home. Lock and unlock your door with your phone, and give keyless entry to family, friends, housekeepers, and other home services without worrying about lost or copied keys.",
                            IsAvailable = true,
                            Title = "August Wi-Fi Smart Lock Pro",
                            UpdatedAt = new DateTime(2024, 6, 3, 16, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ArticleCode = "ECHO0004",
                            BasePrice = 9999m,
                            CreatedAt = new DateTime(2024, 6, 4, 11, 15, 0, 0, DateTimeKind.Utc),
                            Description = "The Amazon Echo (4th Gen) is a hands-free smart speaker that you control with your voice. It connects to Alexa to play music, make calls, set alarms and timers, ask questions, control smart home devices, and more.",
                            IsAvailable = true,
                            Title = "Amazon Echo (4th Gen)",
                            UpdatedAt = new DateTime(2024, 6, 4, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ArticleCode = "RING0001",
                            BasePrice = 19999m,
                            CreatedAt = new DateTime(2024, 6, 5, 13, 20, 0, 0, DateTimeKind.Utc),
                            Description = "The Ring Spotlight Cam is a wireless security camera that lets you see, hear, and speak to anyone on your property from your phone, tablet, or PC. It has built-in spotlights and a siren to deter intruders, and it works with Alexa to let you control it with your voice.",
                            IsAvailable = true,
                            Title = "Ring Spotlight Cam",
                            UpdatedAt = new DateTime(2024, 6, 5, 13, 20, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ArticleDetailNumeric", b =>
                {
                    b.Property<string>("ArticleCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("DetailSlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ArticleCode", "DetailSlug");

                    b.HasIndex("DetailSlug");

                    b.ToTable("ArticleDetailNumeric", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleCode = "NEST0003",
                            DetailSlug = "power",
                            Value = 24m
                        },
                        new
                        {
                            ArticleCode = "NEST0003",
                            DetailSlug = "width",
                            Value = 84m
                        },
                        new
                        {
                            ArticleCode = "NEST0003",
                            DetailSlug = "height",
                            Value = 84m
                        },
                        new
                        {
                            ArticleCode = "NEST0003",
                            DetailSlug = "depth",
                            Value = 28m
                        },
                        new
                        {
                            ArticleCode = "NEST0003",
                            DetailSlug = "screen-size",
                            Value = 2.0m
                        },
                        new
                        {
                            ArticleCode = "AUGL0001",
                            DetailSlug = "battery-size",
                            Value = 3000m
                        },
                        new
                        {
                            ArticleCode = "AUGL0001",
                            DetailSlug = "weight",
                            Value = 400m
                        },
                        new
                        {
                            ArticleCode = "PHUE0002",
                            DetailSlug = "power",
                            Value = 9m
                        },
                        new
                        {
                            ArticleCode = "PHUE0002",
                            DetailSlug = "weight",
                            Value = 72m
                        },
                        new
                        {
                            ArticleCode = "ECHO0004",
                            DetailSlug = "weight",
                            Value = 970m
                        },
                        new
                        {
                            ArticleCode = "ECHO0004",
                            DetailSlug = "power",
                            Value = 15m
                        },
                        new
                        {
                            ArticleCode = "RING0001",
                            DetailSlug = "power",
                            Value = 8m
                        },
                        new
                        {
                            ArticleCode = "RING0001",
                            DetailSlug = "weight",
                            Value = 480m
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ArticleDetailText", b =>
                {
                    b.Property<string>("ArticleCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("DetailSlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ArticleCode", "DetailSlug");

                    b.HasIndex("DetailSlug");

                    b.ToTable("ArticleDetailText", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleCode = "NEST0003",
                            DetailSlug = "compatibility",
                            Value = "Works with Alexa, Google Assistant, and Apple HomeKit"
                        },
                        new
                        {
                            ArticleCode = "NEST0003",
                            DetailSlug = "display",
                            Value = "24-bit color LCD, 480 x 480 resolution at 229 pixels per inch (PPI)"
                        },
                        new
                        {
                            ArticleCode = "AUGL0001",
                            DetailSlug = "connectivity",
                            Value = "Wi-Fi and Bluetooth"
                        },
                        new
                        {
                            ArticleCode = "AUGL0001",
                            DetailSlug = "compatibility",
                            Value = "Works with Alexa, Google Assistant, and Siri"
                        },
                        new
                        {
                            ArticleCode = "AUGL0001",
                            DetailSlug = "battery",
                            Value = "Uses four AA batteries (included), lasts up to 6 months depending on usage"
                        },
                        new
                        {
                            ArticleCode = "PHUE0002",
                            DetailSlug = "color-temperature",
                            Value = "Adjustable from warm white (2700K) to daylight (6500K)"
                        },
                        new
                        {
                            ArticleCode = "PHUE0002",
                            DetailSlug = "compatibility",
                            Value = "Works with Alexa, Google Assistant, and Samsung SmartThings"
                        },
                        new
                        {
                            ArticleCode = "ECHO0004",
                            DetailSlug = "connectivity",
                            Value = "Wi-Fi and Bluetooth"
                        },
                        new
                        {
                            ArticleCode = "RING0001",
                            DetailSlug = "video-quality",
                            Value = "1080p HD"
                        },
                        new
                        {
                            ArticleCode = "RING0001",
                            DetailSlug = "audio-quality",
                            Value = "Two-way audio with noise cancellation"
                        },
                        new
                        {
                            ArticleCode = "RING0001",
                            DetailSlug = "connectivity",
                            Value = "Wi-Fi and Ethernet"
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ArticleImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id", "ArticleCode");

                    b.HasIndex("ArticleCode", "OrderIndex")
                        .IsUnique();

                    b.ToTable("ArticleImage", (string)null);
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Detail", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Slug");

                    b.ToTable("Detail", (string)null);

                    b.HasData(
                        new
                        {
                            Slug = "audio",
                            Title = "Audio"
                        },
                        new
                        {
                            Slug = "audio-quality",
                            Title = "Audio Quality"
                        },
                        new
                        {
                            Slug = "battery",
                            Title = "Battery"
                        },
                        new
                        {
                            Slug = "brand",
                            Title = "Brand"
                        },
                        new
                        {
                            Slug = "camera",
                            Title = "Camera"
                        },
                        new
                        {
                            Slug = "color",
                            Title = "Color"
                        },
                        new
                        {
                            Slug = "color-temperature",
                            Title = "Color Temperature"
                        },
                        new
                        {
                            Slug = "compatibility",
                            Title = "Compatibility"
                        },
                        new
                        {
                            Slug = "connectivity",
                            Title = "Connectivity"
                        },
                        new
                        {
                            Slug = "display",
                            Title = "Display"
                        },
                        new
                        {
                            Slug = "features",
                            Title = "Features"
                        },
                        new
                        {
                            Slug = "material",
                            Title = "Material"
                        },
                        new
                        {
                            Slug = "model",
                            Title = "Model"
                        },
                        new
                        {
                            Slug = "operating-system",
                            Title = "Operating System"
                        },
                        new
                        {
                            Slug = "ports",
                            Title = "Ports"
                        },
                        new
                        {
                            Slug = "processor",
                            Title = "Processor"
                        },
                        new
                        {
                            Slug = "resolution",
                            Title = "Resolution"
                        },
                        new
                        {
                            Slug = "video-quality",
                            Title = "Video Quality"
                        },
                        new
                        {
                            Slug = "battery-size",
                            Title = "Battery Size",
                            Unit = "mAh"
                        },
                        new
                        {
                            Slug = "depth",
                            Title = "Depth",
                            Unit = "millimeters"
                        },
                        new
                        {
                            Slug = "height",
                            Title = "Height",
                            Unit = "millimeters"
                        },
                        new
                        {
                            Slug = "power",
                            Title = "Power",
                            Unit = "watts"
                        },
                        new
                        {
                            Slug = "ram-size",
                            Title = "RAM Size",
                            Unit = "GB"
                        },
                        new
                        {
                            Slug = "refresh-rate",
                            Title = "Refresh Rate",
                            Unit = "Hz"
                        },
                        new
                        {
                            Slug = "screen-size",
                            Title = "Screen Size",
                            Unit = "inches"
                        },
                        new
                        {
                            Slug = "storage",
                            Title = "Storage",
                            Unit = "GB"
                        },
                        new
                        {
                            Slug = "weight",
                            Title = "Weight",
                            Unit = "grams"
                        },
                        new
                        {
                            Slug = "width",
                            Title = "Width",
                            Unit = "millimeters"
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Discount", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ArticleCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code", "ArticleCode");

                    b.HasIndex("ArticleCode");

                    b.ToTable("Discount", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "WINTER25",
                            ArticleCode = "PHUE0002",
                            Percentage = 0.25m,
                            ValidFrom = new DateTime(2025, 11, 19, 23, 0, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2026, 3, 19, 23, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ArticleDetailNumeric", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Article", "Article")
                        .WithMany("ArticleDetailNumerics")
                        .HasForeignKey("ArticleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Detail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ArticleDetailText", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Article", "Article")
                        .WithMany("ArticleDetailTexts")
                        .HasForeignKey("ArticleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Detail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.ArticleImage", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Article", "Article")
                        .WithMany("ArticleImages")
                        .HasForeignKey("ArticleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Discount", b =>
                {
                    b.HasOne("Matterway.Catalog.Api.Domain.Entities.Article", "Article")
                        .WithMany("Discounts")
                        .HasForeignKey("ArticleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Matterway.Catalog.Api.Domain.Entities.Article", b =>
                {
                    b.Navigation("ArticleDetailNumerics");

                    b.Navigation("ArticleDetailTexts");

                    b.Navigation("ArticleImages");

                    b.Navigation("Discounts");
                });
#pragma warning restore 612, 618
        }
    }
}
