// <auto-generated />
using System;
using Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.API.Migrations;

[DbContext(typeof(CatalogDbContext))]
[Migration("20230410150316_Initialize")]
partial class Initialize
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Catalog.API.Entities.Product", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsAvailable")
                    .HasColumnType("bit");

                b.Property<double?>("Price")
                    .IsRequired()
                    .HasColumnType("float");

                b.Property<string>("ProductCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("UpdatedAt")
                    .IsRequired()
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Product");
            });

        modelBuilder.Entity("Catalog.API.Entities.ProductDetail", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<string>("Unit")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("ProductId");

                b.ToTable("ProductDetail");
            });

        modelBuilder.Entity("Catalog.API.Entities.ProductImage", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ImageAlt")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageUrl")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsMain")
                    .HasColumnType("bit");

                b.HasKey("Id", "ProductId");

                b.HasIndex("ProductId");

                b.ToTable("ProductImage");
            });

        modelBuilder.Entity("Catalog.API.Entities.ProductDetail", b =>
            {
                b.HasOne("Catalog.API.Entities.Product", "Product")
                    .WithMany("ProductDetails")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");
            });

        modelBuilder.Entity("Catalog.API.Entities.ProductImage", b =>
            {
                b.HasOne("Catalog.API.Entities.Product", "Product")
                    .WithMany("ProductImages")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");
            });

        modelBuilder.Entity("Catalog.API.Entities.Product", b =>
            {
                b.Navigation("ProductDetails");

                b.Navigation("ProductImages");
            });
#pragma warning restore 612, 618
    }
}
