version: '3.4'

services:
  webstore.web:
    container_name: webstore-web
    image: ${DOCKER_REGISTRY-}webstore-web
    environment:
      NUXT_APP_VERSION: "1.0.0"
    command: node /app/.output/server/index.mjs
    tty: true
    build:
      context: src/Clients/Webstore
      dockerfile: Dockerfile

  catalog.api:
    container_name: catalog-api
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  customers.api:
    container_name: customers-api
    image: ${DOCKER_REGISTRY-}customers-api
    build:
      context: .
      dockerfile: src/Services/Customers/Customers.API/Dockerfile


  identity.api:
    container_name: identity-api
    image: ${DOCKER_REGISTRY-}identity-api
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile


  inventory.api:
    container_name: inventory-api
    image: ${DOCKER_REGISTRY-}inventory-api
    build:
      context: .
      dockerfile: src/Services/Inventory/Inventory.API/Dockerfile


  ordering.api:
    container_name: ordering-api
    image: ${DOCKER_REGISTRY-}ordering-api
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile


  payment.api:
    container_name: payment-api
    image: ${DOCKER_REGISTRY-}payment-api
    build:
      context: .
      dockerfile: src/Services/Payments/Payments.API/Dockerfile

