version: '3.4'

services:
  storefront.web:
    environment:
      - NUXT_PUBLIC_APP_DOMAIN=localhost
      - NUXT_PUBLIC_AUTH_API_BASE_URL=http://localhost:2003
      - NUXT_PUBLIC_CATALOG_API_BASE_URL=http://localhost:2001
      - NUXT_PUBLIC_CUSTOMERS_API_BASE_URL=http://localhost:2002
      - NUXT_PUBLIC_ORDERING_API_BASE_URL=http://localhost:2005
      - NUXT_SERVER_ORDERING_API_BASE_URL=http://ordering-api:80
      - NUXT_SERVER_PAYMENTS_API_BASE_URL=http://payments-api:80
    ports:
      - '3001:3000'
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__CatalogDbContext=Server=sqlserver;Database=catalog;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity-api:80
    depends_on:
      - sqlserver
    ports:
      - '2001:80'
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro

  customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__CustomersDbContext=Server=sqlserver;Database=customers;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity-api:80
      - Services__Catalog__Url=http://catalog-api:80
    depends_on:
      - sqlserver
    ports:
      - '2002:80'
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__IdentityDbContext=Server=sqlserver;Database=identity;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
    depends_on:
      - sqlserver
    ports:
      - '2003:80'
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro

  inventory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__InventoryDbContext=Server=sqlserver;Database=inventory;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity-api:80
    depends_on:
      - sqlserver
    ports:
      - '2004:80'
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__OrderingDbContext=Server=sqlserver;Database=ordering;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity-api:80
      - Services__Catalog__Url=http://catalog-api:80
      - Services__Customers__Url=http://customers-api:80
    depends_on:
      - sqlserver
    ports:
      - '2005:80'
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro

  payments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PaymentsDbContext=Server=sqlserver;Database=payments;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity-api:80
    depends_on:
      - sqlserver
    ports:
      - '2006:80'
    volumes:
      - ${HOME}/.microsoft/usersecrets:${HOME}/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:${HOME}/.aspnet/https:ro
    command: dotnet dev-certs https; dotnet dev-certs https --trust

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1401:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=M55QL_4UTH
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
