version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__CatalogDbContext=Server=catalog_db;Database=catalog;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity_api:80
    ports:
      - "2001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__CustomersDbContext=Server=customers_db;Database=customers;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity_api:80
      - Services__Catalog__Url=http://catalog_api:80
    ports:
      - "2002:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__IdentityDbContext=Server=identity_db;Database=identity;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
    ports:
      - "2003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
     
  inventory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__InventoryDbContext=Server=inventory_db;Database=inventory;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity_api:80
    ports:
      - "2004:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__OrderingDbContext=Server=ordering_db;Database=ordering;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity_api:80
      - Services__Catalog__Url=http://catalog_api:80
      - Services__Customers__Url=http://customers_api:80
    ports:
      - "2005:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__PaymentsDbContext=Server=payment_db;Database=payment;User=SA;Password=M55QL_4UTH;TrustServerCertificate=True;
      - Jwt__Issuer=http://localhost:2003
      - Jwt__Key=2b23549ce5404449bf7b41a56856bfab
      - Jwt__Audience=http://localhost:2003
      - Services__Identity__Url=http://identity_api:80
    ports:
      - "2006:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  catalog.db:
    container_name: catalog_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1401:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M55QL_4UTH
      - MSSQL_PID=Express

  customers.db:
    container_name: customers_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1402:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M55QL_4UTH
      - MSSQL_PID=Express

  identity.db:
    container_name: identity_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1403:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M55QL_4UTH
      - MSSQL_PID=Express

  inventory.db:
    container_name: inventory_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1404:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M55QL_4UTH
      - MSSQL_PID=Express

  ordering.db:
    container_name: ordering_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1405:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M55QL_4UTH
      - MSSQL_PID=Express

  payment.db:
    container_name: payment_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1406:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M55QL_4UTH
      - MSSQL_PID=Express
