// <auto-generated />
using System;
using Matterway.Payments.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matterway.Payments.Api.Migrations
{
    [DbContext(typeof(PaymentsDb))]
    [Migration("20251111001603_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Payments.Api.Features.Payments.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PaymentAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentState")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            CardHolder = "Mara Jakov",
                            CardNumber = "1234-5678-1234-5678",
                            ExpirationDate = "12/26",
                            PaymentAmount = 39998.0,
                            PaymentDate = new DateTime(2024, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaymentState = 1,
                            ReferenceNumber = "5655-6666-7877",
                            SecurityCode = "1234"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            CardHolder = "Stefan Stefanov",
                            CardNumber = "8856-5678-1234-3366",
                            ExpirationDate = "06/24",
                            PaymentAmount = 4999.0,
                            PaymentDate = new DateTime(2024, 6, 2, 11, 30, 0, 0, DateTimeKind.Utc),
                            PaymentState = 1,
                            ReferenceNumber = "6666-8888-6588",
                            SecurityCode = "6658"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
