// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ordering.API.Data;

#nullable disable

namespace Ordering.API.Migrations;

[DbContext(typeof(OrderingDbContext))]
[Migration("20230410124050_Initialize")]
partial class Initialize
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Ordering.API.Entities.Address", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Country")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Note")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ReceiverName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Residence")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Street")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ZipCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Address");
            });

        modelBuilder.Entity("Ordering.API.Entities.Order", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("DeliveryAddressId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ReferenceNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("DeliveryAddressId");

                b.ToTable("Order");
            });

        modelBuilder.Entity("Ordering.API.Entities.OrderHistory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("OrderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("OrderStatus")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("OrderHistory");
            });

        modelBuilder.Entity("Ordering.API.Entities.OrderItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("OrderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ProductName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("UnitPrice")
                    .HasColumnType("float");

                b.Property<int>("Units")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("OrderItem");
            });

        modelBuilder.Entity("Ordering.API.Entities.Order", b =>
            {
                b.HasOne("Ordering.API.Entities.Address", "Address")
                    .WithMany()
                    .HasForeignKey("DeliveryAddressId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Address");
            });

        modelBuilder.Entity("Ordering.API.Entities.OrderHistory", b =>
            {
                b.HasOne("Ordering.API.Entities.Order", "Order")
                    .WithMany("OrderHistories")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Order");
            });

        modelBuilder.Entity("Ordering.API.Entities.OrderItem", b =>
            {
                b.HasOne("Ordering.API.Entities.Order", "Order")
                    .WithMany("OrderItems")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Order");
            });

        modelBuilder.Entity("Ordering.API.Entities.Order", b =>
            {
                b.Navigation("OrderHistories");

                b.Navigation("OrderItems");
            });
#pragma warning restore 612, 618
    }
}
