// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ordering.API.Data;

#nullable disable

namespace Ordering.API.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    partial class OrderingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ordering.API.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            City = "Sremska Mitrovica",
                            Country = "Serbia",
                            ReceiverName = "Mara Jakov",
                            Residence = "54",
                            Street = "Njegoševa",
                            ZipCode = "22000"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            City = "Novi Sad",
                            Country = "Serbia",
                            ReceiverName = "Stefan Stefanov",
                            Residence = "3",
                            Street = "Narodnih Heroja",
                            ZipCode = "21000"
                        });
                });

            modelBuilder.Entity("Ordering.API.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryAddressId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b6"),
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            DeliveryAddressId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            ReferenceNumber = "5655-6666-7877"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            DeliveryAddressId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            ReferenceNumber = "6666-8888-6588"
                        });
                });

            modelBuilder.Entity("Ordering.API.Entities.OrderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderHistory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            CreatedDate = new DateTime(2023, 5, 19, 22, 14, 38, 723, DateTimeKind.Local).AddTicks(6554),
                            Description = "Order Ready",
                            OrderId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b6"),
                            OrderStatus = 1
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b8"),
                            CreatedDate = new DateTime(2023, 5, 19, 22, 14, 38, 723, DateTimeKind.Local).AddTicks(6560),
                            Description = "Order Canceled",
                            OrderId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            OrderStatus = 5
                        });
                });

            modelBuilder.Entity("Ordering.API.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId", "ProductId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b6"),
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            ProductName = "Ring Spotlight Cam",
                            Quantity = 2,
                            UnitPrice = 19999.0
                        },
                        new
                        {
                            OrderId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            ProductName = "Philips Hue White and Color Ambiance A19 Smart LED Bulb",
                            Quantity = 1,
                            UnitPrice = 4999.0
                        });
                });

            modelBuilder.Entity("Ordering.API.Entities.Order", b =>
                {
                    b.HasOne("Ordering.API.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Ordering.API.Entities.OrderHistory", b =>
                {
                    b.HasOne("Ordering.API.Entities.Order", "Order")
                        .WithMany("OrderHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ordering.API.Entities.OrderItem", b =>
                {
                    b.HasOne("Ordering.API.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ordering.API.Entities.Order", b =>
                {
                    b.Navigation("OrderHistory");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
