#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/Ordering.Api/Ordering.Api.csproj", "src/Ordering.Api/"]
RUN dotnet restore "src/Ordering.Api/Ordering.Api.csproj"
COPY . .
WORKDIR "/src/src/Ordering.Api"
RUN dotnet build "Ordering.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Ordering.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
ARG ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
COPY --from=publish /app/publish .
COPY src/Ordering.Api/Properties/ ./Properties/
ENTRYPOINT ["dotnet", "Ordering.Api.dll"]
