name: "matterway-erp-stack"
services:
  matterway-platform-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    container_name: "aspire-dashboard"
    ports:
      - "18888:18888"
    expose:
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  sql-server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQLSERVERPASSWORD}"
    ports:
      - "1401:1433"
    expose:
      - "1433"
    volumes:
      - type: "volume"
        target: "/var/opt/mssql"
        source: "matterway.apphost-5993ba3ed5-sql-server-data"
        read_only: false
    networks:
      - "aspire"
    restart: "unless-stopped"
  identity-api:
    image: "${IDENTITY_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${IDENTITY_API_PORT}"
      ConnectionStrings__IdentityDb: "Server=sql-server,1433;User ID=sa;Password=${SQLSERVERPASSWORD};TrustServerCertificate=true;Initial Catalog=IdentityDb"
      Jwt__Key: "${JWTSIGNINGKEY}"
      Jwt__Issuer: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Audience: "http://identity-api:${IDENTITY_API_PORT}"
      services__storefront-web__http__0: "http://storefront-web:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://matterway-platform-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "identity-api"
    ports:
      - "2003:8080"
    networks:
      - "aspire"
    restart: "unless-stopped"
  catalog-api:
    image: "${CATALOG_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${CATALOG_API_PORT}"
      ConnectionStrings__CatalogDb: "Server=sql-server,1433;User ID=sa;Password=${SQLSERVERPASSWORD};TrustServerCertificate=true;Initial Catalog=CatalogDb"
      services__identity-api__http__0: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Key: "${JWTSIGNINGKEY}"
      Jwt__Issuer: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Audience: "http://identity-api:${IDENTITY_API_PORT}"
      services__storefront-web__http__0: "http://storefront-web:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://matterway-platform-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "catalog-api"
    ports:
      - "2001:8080"
    networks:
      - "aspire"
    restart: "unless-stopped"
  customers-api:
    image: "${CUSTOMERS_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${CUSTOMERS_API_PORT}"
      ConnectionStrings__CustomersDb: "Server=sql-server,1433;User ID=sa;Password=${SQLSERVERPASSWORD};TrustServerCertificate=true;Initial Catalog=CustomersDb"
      services__identity-api__http__0: "http://identity-api:${IDENTITY_API_PORT}"
      services__catalog-api__http__0: "http://catalog-api:${CATALOG_API_PORT}"
      Jwt__Key: "${JWTSIGNINGKEY}"
      Jwt__Issuer: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Audience: "http://identity-api:${IDENTITY_API_PORT}"
      services__storefront-web__http__0: "http://storefront-web:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://matterway-platform-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "customers-api"
    ports:
      - "2002:8080"
    networks:
      - "aspire"
    restart: "unless-stopped"
  inventory-api:
    image: "${INVENTORY_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${INVENTORY_API_PORT}"
      services__identity-api__http__0: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Key: "${JWTSIGNINGKEY}"
      Jwt__Issuer: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Audience: "http://identity-api:${IDENTITY_API_PORT}"
      services__storefront-web__http__0: "http://storefront-web:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://matterway-platform-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "inventory-api"
    ports:
      - "2004:8080"
    networks:
      - "aspire"
    restart: "unless-stopped"
  ordering-api:
    image: "${ORDERING_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${ORDERING_API_PORT}"
      ConnectionStrings__OrderingDb: "Server=sql-server,1433;User ID=sa;Password=${SQLSERVERPASSWORD};TrustServerCertificate=true;Initial Catalog=OrderingDb"
      services__identity-api__http__0: "http://identity-api:${IDENTITY_API_PORT}"
      services__catalog-api__http__0: "http://catalog-api:${CATALOG_API_PORT}"
      services__customers-api__http__0: "http://customers-api:${CUSTOMERS_API_PORT}"
      Jwt__Key: "${JWTSIGNINGKEY}"
      Jwt__Issuer: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Audience: "http://identity-api:${IDENTITY_API_PORT}"
      services__storefront-web__http__0: "http://storefront-web:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://matterway-platform-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "ordering-api"
    ports:
      - "2005:8080"
    networks:
      - "aspire"
    restart: "unless-stopped"
  payments-api:
    image: "${PAYMENTS_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${PAYMENTS_API_PORT}"
      ConnectionStrings__PaymentsDb: "Server=sql-server,1433;User ID=sa;Password=${SQLSERVERPASSWORD};TrustServerCertificate=true;Initial Catalog=PaymentsDb"
      services__identity-api__http__0: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Key: "${JWTSIGNINGKEY}"
      Jwt__Issuer: "http://identity-api:${IDENTITY_API_PORT}"
      Jwt__Audience: "http://identity-api:${IDENTITY_API_PORT}"
      services__storefront-web__http__0: "http://storefront-web:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://matterway-platform-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "payments-api"
    ports:
      - "2006:8080"
    networks:
      - "aspire"
    restart: "unless-stopped"
  storefront-web:
    image: "${STOREFRONT_WEB_IMAGE}"
    environment:
      NODE_ENV: "production"
      NUXT_SERVER_ORDERING_API_BASE_URL: "http://ordering-api:${ORDERING_API_PORT}"
      NUXT_SERVER_PAYMENTS_API_BASE_URL: "http://payments-api:${PAYMENTS_API_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://matterway-platform-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "storefront-web"
    ports:
      - "3001:3000"
    depends_on:
      catalog-api:
        condition: "service_started"
    networks:
      - "aspire"
    restart: "unless-stopped"
networks:
  aspire:
    driver: "bridge"
volumes:
  matterway.apphost-5993ba3ed5-sql-server-data:
    driver: "local"
