<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>3a20eb34-e04f-40a6-a682-c367fd6611a1</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.Docker" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6"/>
        <PackageReference Include="Scalar.Aspire" Version="0.9.37"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Matterway.Catalog.Api\Matterway.Catalog.Api.csproj"/>
        <ProjectReference Include="..\Matterway.Customers.Api\Matterway.Customers.Api.csproj"/>
        <ProjectReference Include="..\Matterway.Identity.Api\Matterway.Identity.Api.csproj"/>
        <ProjectReference Include="..\Matterway.Migrations\Matterway.Migrations.csproj"/>
        <ProjectReference Include="..\Matterway.Sales.Api\Matterway.Sales.Api.csproj"/>
        <ProjectReference Include="..\Matterway.ServiceDefaults\Matterway.ServiceDefaults.csproj" IsAspireProjectResource="false"/>
    </ItemGroup>

</Project>
