<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>b729ab1f-4771-4e7e-be8d-4f99f4ab8e37</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..\</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="8.1.0"/>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0"/>
        <PackageReference Include="AutoMapper" Version="15.1.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0-preview.4"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Matterway.ServiceDefaults\Matterway.ServiceDefaults.csproj"/>
    </ItemGroup>

    <Import Project="..\Matterway.Common\Matterway.Common.projitems" Label="Shared"/>

</Project>
