// <auto-generated />
using System;
using Matterway.Identity.Api.Providers.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matterway.Identity.Api.Migrations
{
    [DbContext(typeof(IdentityDbComposer))]
    partial class IdentityDbComposerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Identity.Api.Domain.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d5f0a44-e0f6-4b13-8a06-1dc8db48fe74",
                            Created = new DateTime(2021, 9, 9, 10, 10, 10, 0, DateTimeKind.Utc),
                            Email = "mladen@matterway.local",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MLADEN@MATTERWAY.LOCAL",
                            NormalizedUserName = "MLADEN@MATTERWAY.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEF0PUBp9R90/+4Ul8J4HdcOJNNv1Ol5W2vIK2ooqOFRTc1vcgJtxBVqWYlONUSjEJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a1f3895-9229-45c9-9fcb-7b8f2a9f46b3",
                            TwoFactorEnabled = false,
                            UserName = "mladen@matterway.local"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb6a7ad6-7c4c-4bb6-bce5-8aa4d1bf7b58",
                            Created = new DateTime(2022, 10, 10, 11, 11, 11, 0, DateTimeKind.Utc),
                            Email = "jelena@matterway.local",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JELENA@MATTERWAY.LOCAL",
                            NormalizedUserName = "JELENA@MATTERWAY.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEJru7jHMkz3Cdn5rk9dTj3umC8lMLv0XfkY1k5PXeuh2VkwiazogHTe8IoEhYWr6rg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf0cb1b8-d485-4fdd-8a89-fb70120dbd9f",
                            TwoFactorEnabled = false,
                            UserName = "jelena@matterway.local"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f53e60a2-c944-4622-af21-b3afa3d7a00c",
                            Created = new DateTime(2023, 4, 12, 12, 10, 0, 0, DateTimeKind.Utc),
                            Email = "stefan999@mail.local",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STEFAN999@MAIL.LOCAL",
                            NormalizedUserName = "STEFAN999@MAIL.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEFSn2wwtXMTkX5P1GglolnIwSI7iauwvIgZXlrTih7oTJ/FWJkY/CXmdNCR4ZJKAug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "019bada3-b4dc-7155-baca-576dd9914d57",
                            TwoFactorEnabled = false,
                            UserName = "stefan999@mail.local"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3b9f3e46-3c3c-4f04-9b6f-4fe90f0a8c80",
                            Created = new DateTime(2024, 2, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "marag@mail.local",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARAG@MAIL.LOCAL",
                            NormalizedUserName = "MARAG@MAIL.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEEPDW3c2GRf473Cn5iK6pW8vBqQuPvei43fnIK+WbTaixjrzkd/mMyXGIp2+IoDI8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ca7016d-0e4d-4b92-96cb-c964d7d8f9c1",
                            TwoFactorEnabled = false,
                            UserName = "marag@mail.local"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f055a46-6bf0-4fdb-8c27-1877a2b6f811"),
                            ConcurrencyStamp = "f9f0b98d-7d9e-48d8-86c5-9a13ebf1c81a",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("35a11f01-15f0-4110-8efc-f81e537b0c94"),
                            ConcurrencyStamp = "ea4804c9-5cc8-4a56-9a06-3f7d76715a56",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("c4c29ba9-3b22-416f-8a37-8a7c3d6ed1f9"),
                            ConcurrencyStamp = "a40b1c8b-7f9f-4cbb-9de8-8c79d9f0dd8e",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            RoleId = new Guid("6f055a46-6bf0-4fdb-8c27-1877a2b6f811")
                        },
                        new
                        {
                            UserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b2"),
                            RoleId = new Guid("35a11f01-15f0-4110-8efc-f81e537b0c94")
                        },
                        new
                        {
                            UserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            RoleId = new Guid("c4c29ba9-3b22-416f-8a37-8a7c3d6ed1f9")
                        },
                        new
                        {
                            UserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            RoleId = new Guid("c4c29ba9-3b22-416f-8a37-8a7c3d6ed1f9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Matterway.Identity.Api.Domain.Entities.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Matterway.Identity.Api.Domain.Entities.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matterway.Identity.Api.Domain.Entities.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Matterway.Identity.Api.Domain.Entities.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
