// <auto-generated />
using System;
using Matterway.Ordering.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matterway.Ordering.Api.Migrations
{
    [DbContext(typeof(OrderingDb))]
    [Migration("20251108174109_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Ordering.Api.Features.Addresses.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            City = "Sremska Mitrovica",
                            Country = "Serbia",
                            ReceiverName = "Mara Jakov",
                            Residence = "54",
                            Street = "Njegoševa",
                            ZipCode = "22000"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            City = "Novi Sad",
                            Country = "Serbia",
                            ReceiverName = "Stefan Stefanov",
                            Residence = "3",
                            Street = "Narodnih Heroja",
                            ZipCode = "21000"
                        });
                });

            modelBuilder.Entity("Matterway.Ordering.Api.Features.OrderHistories.Domain.OrderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderHistory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            CreatedDate = new DateTime(2024, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Order Ready",
                            OrderId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b6"),
                            OrderStatus = 1
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b8"),
                            CreatedDate = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Order Canceled",
                            OrderId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            OrderStatus = 5
                        });
                });

            modelBuilder.Entity("Matterway.Ordering.Api.Features.OrderItems.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("OrderId", "ProductId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b6"),
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            ProductName = "Ring Spotlight Cam",
                            Quantity = 2,
                            UnitPrice = 19999.0
                        },
                        new
                        {
                            OrderId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            ProductName = "Philips Hue White and Color Ambiance A19 Smart LED Bulb",
                            Quantity = 1,
                            UnitPrice = 4999.0
                        });
                });

            modelBuilder.Entity("Matterway.Ordering.Api.Features.Orders.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryAddressId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b6"),
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            DeliveryAddressId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            ReferenceNumber = "5655-6666-7877"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            DeliveryAddressId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            ReferenceNumber = "6666-8888-6588"
                        });
                });

            modelBuilder.Entity("Matterway.Ordering.Api.Features.OrderHistories.Domain.OrderHistory", b =>
                {
                    b.HasOne("Matterway.Ordering.Api.Features.Orders.Domain.Order", "Order")
                        .WithMany("OrderHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Matterway.Ordering.Api.Features.OrderItems.Domain.OrderItem", b =>
                {
                    b.HasOne("Matterway.Ordering.Api.Features.Orders.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Matterway.Ordering.Api.Features.Orders.Domain.Order", b =>
                {
                    b.HasOne("Matterway.Ordering.Api.Features.Addresses.Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Matterway.Ordering.Api.Features.Orders.Domain.Order", b =>
                {
                    b.Navigation("OrderHistory");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
