@startuml SUIdentityUseCaseDiagram
title SU: Identity - Use Case Diagram
left to right direction
skinparam shadowing false
skinparam actorStyle hollow

actor user as "User"

together {
  actor empl as "Employee"
  actor sysm as "System"
}

user <|-- empl

package "Identity" {
  together {
    usecase signIn as "Sign In"
    usecase refreshSession as "Refresh Session"
    usecase signOut as "Sign Out"
  }

  usecase manageSystemUsers as "Manage System Users
                                ..<i>extension points</i>..
                                Delete System User [manager only]"
  usecase deleteSystemUser as "Delete System User"
  usecase viewSystemUsers as "View System Users"

  together {
    usecase viewUserPermissions as "View User Permissions"
    usecase manageUserPermissions as "Manage User Permissions"
    usecase createEmployeeAccount as "Create Employee User Account"
  }

  together {
    usecase createCustomerAccount as "Create Customer User Account"
    usecase introspectAccessToken as "Introspect Access Token"
  }

  manageUserPermissions .u.> viewUserPermissions : <<include>>
  manageSystemUsers .u.> viewSystemUsers : <<include>>
  manageSystemUsers <.u. deleteSystemUser : <<extend>>
}

user --- signIn
user --- refreshSession
user --- signOut

manageSystemUsers --- empl : perm:[operator,manager]

manageUserPermissions --- empl : perm:[manager]
createEmployeeAccount --- empl : perm:[manager]

introspectAccessToken --- sysm
createCustomerAccount --- sysm
@enduml
