@startuml SUSalesUseCaseDiagram
title SU: Sales - Use Case Diagram
left to right direction
skinparam shadowing false
skinparam actorStyle hollow

actor user as "User"
actor csmr as "Customer"
actor empl as "Employee"

user <|-- csmr
user <|-- empl

actor systm as "Storefront Web"

package "Sales" {
  usecase viewOwnOrders as "View Own Orders"

  usecase viewOrders as "View Orders
                         ..<i>extension points</i>..
                         View Payments"
  usecase viewPayments as "View Payments"
  usecase updateOrderStatus as "Add Order Status"

  usecase registerPayment as "Register Payment"
  usecase placeOrder as "Place Order"

  viewPayments .r.> viewOrders : <<extend>>
}

csmr --- placeOrder
csmr --- viewOwnOrders

updateOrderStatus --- empl : perm:[operator,manager]
viewOrders --- empl : perm:[observer,operator,manager]
placeOrder --- systm

registerPayment --- systm
@enduml
