@startuml SUCustomersUseCaseDiagram
title SU: Customers - Use Case Diagram
left to right direction
skinparam shadowing false
skinparam actorStyle hollow

together {
  actor user as "User"
  actor csmr as "Customer"
}

actor empl as "Employee"
actor sales as "Sales Service"
actor identity as "Identity Service"

user <|-- csmr
user <|-l- empl

package "Customers" {
  usecase syncOnOrder as "Create Order Snapshot from Cart"

  usecase createCustomer as "Register Customer"
  usecase manageOwnProfile as "Manage Own Profile"
  usecase manageOwnAddress as "Manage Own Address"
  usecase manageOwnCartItems as "Manage Own Cart Items"

  usecase manageCustomers as "Manage Customers
                              ..<i>extension points</i>..
                              Upsert Customer Address"
  usecase viewCustomers as "View Customers"
  usecase viewCustomerAddress as "View Customer Address"
  usecase manageCustomerAddress as "Manage Customer Address"

  manageCustomerAddress .l.> manageCustomers : <<extend>>
  manageCustomerAddress .r.> viewCustomerAddress : <<include>>
  manageCustomers .l.> viewCustomers : <<include>>
}

user -- createCustomer
createCustomer -- identity
csmr -- manageOwnProfile
csmr -- manageOwnAddress
csmr -- manageOwnCartItems

syncOnOrder -- sales

viewCustomers -- empl : perm:[observer,operator,manager]
viewCustomerAddress -- empl : perm:[observer,operator,manager]
manageCustomers -- empl : perm:[operator,manager]
manageCustomerAddress -- empl : perm:[operator,manager]
@enduml
