@startuml SUCatalogUseCaseDiagram
title SU: Catalog - Use Case Diagram
left to right direction
skinparam shadowing false
skinparam actorStyle hollow

actor user as "User"
actor empl as "Employee"

user <|-- empl

package "Catalog" {
  usecase viewDetailedArticles as "View Article Details"
  usecase viewDiscounts as "View Active Discounts"
  usecase queryArticles as "Query Articles
                           ..<i>extension points</i>..
                           View Article Details"
  queryArticles <.. viewDetailedArticles: <<extend>>
  queryArticles ..> viewDiscounts: <<include>>

  usecase manageArticles as "Manage Articles"
  usecase manageArticleDetails as "Manage Article Details"
  usecase manageArticleImages as "Manage Article Images"
  usecase manageDiscounts as "Manage Discounts"
  usecase viewManagedDiscounts as "View Managed Discounts"
  manageDiscounts ..> viewManagedDiscounts : <<include>>
  manageArticleDetails <.. manageArticles : <<include>>
  manageArticleImages <.. manageArticles : <<include>>

  usecase viewDetails as "View Detail Definitions"
  usecase manageDetails as "Manage Detail Definitions"
  viewDetails <.. manageDetails : <<include>>

  usecase importCatalogArchive as "Import Catalog Archive"
  usecase exportCatalogArchive as "Export Catalog Archive"
}

user --- queryArticles
user --- viewDetails

manageArticles -- empl : perm:[operator,manager]
viewManagedDiscounts -- empl : perm:[observer,operator,manager]
manageDiscounts -- empl : perm:[operator,manager]
manageDetails -- empl : perm:[operator,manager]
importCatalogArchive -- empl : perm:[manager]
exportCatalogArchive -- empl : perm:[manager]
@enduml
