@startuml SUCustomersUseCaseDiagram
title SU: Customers - Use Case Diagram
left to right direction
skinparam shadowing false
skinparam actorStyle hollow

together {
  actor user as "User"
  actor csmr as "Customer"
}
together  {
  actor empl as "Employee"
  actor sysm as "System"
  sysm -[hidden]l- empl
}

user <|-- csmr
user <|-- empl

package "Customers" {
  usecase syncOnOrder as "Put Order Snapshot by ID"

  usecase createCustomer as "Create Customer"
  usecase manageOwnProfile as "Manage Own Profile"
  usecase manageOwnAddress as "Manage Own Address"
  usecase manageOwnCartItems as "Manage Own Cart Items"

  usecase manageCustomers as "Manage Customers
                              ..<i>extension points</i>..
                              Upsert Customer Address"
  usecase viewCustomers as "View Customers"
  usecase manageCustomerAddress as "Manage Customer Address"

  manageCustomerAddress .r.> manageCustomers : <<extend>>
  manageCustomers .r.> viewCustomers : <<include>>
}

user -- createCustomer
csmr -- manageOwnProfile
csmr -- manageOwnAddress
csmr -- manageOwnCartItems

syncOnOrder -- sysm

viewCustomers -- empl : perm:[observer,operator,manager]
manageCustomers -- empl : perm:[operator,manager]
@enduml
