// <auto-generated />
using System;
using Identity.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Api.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.Api.Features.Sessions.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Identity.Api.Features.SystemUsers.Domain.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Created = new DateTime(2021, 9, 9, 12, 10, 10, 0, DateTimeKind.Local),
                            Email = "mladen@matterway.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEF0PUBp9R90/+4Ul8J4HdcOJNNv1Ol5W2vIK2ooqOFRTc1vcgJtxBVqWYlONUSjEJw==",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b2"),
                            Created = new DateTime(2022, 10, 10, 13, 11, 11, 0, DateTimeKind.Local),
                            Email = "jelena@matterway.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEJru7jHMkz3Cdn5rk9dTj3umC8lMLv0XfkY1k5PXeuh2VkwiazogHTe8IoEhYWr6rg==",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            Created = new DateTime(2023, 4, 12, 14, 10, 0, 0, DateTimeKind.Local),
                            Email = "stefan999@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEFSn2wwtXMTkX5P1GglolnIwSI7iauwvIgZXlrTih7oTJ/FWJkY/CXmdNCR4ZJKAug==",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            Created = new DateTime(2024, 2, 20, 10, 30, 0, 0, DateTimeKind.Local),
                            Email = "marag2@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEEPDW3c2GRf473Cn5iK6pW8vBqQuPvei43fnIK+WbTaixjrzkd/mMyXGIp2+IoDI8Q==",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Identity.Api.Features.Sessions.Domain.Session", b =>
                {
                    b.HasOne("Identity.Api.Features.SystemUsers.Domain.SystemUser", "SystemUser")
                        .WithMany("Sessions")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Identity.Api.Features.SystemUsers.Domain.SystemUser", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
