// <auto-generated />
using System;
using Matterway.Customers.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matterway.Customers.Api.Migrations
{
    [DbContext(typeof(CustomersDbComposer))]
    [Migration("20260302202459_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Address", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            AddressLine1 = "Futog",
                            AddressLine2 = "23b",
                            City = "Novi Sad",
                            ContactPhone = "+381601234567",
                            Country = "Serbia",
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            ZipCode = "21000"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b6"),
                            AddressLine1 = "Kralja Milana",
                            AddressLine2 = "34/10",
                            City = "Beograd",
                            ContactPhone = "+381676543210",
                            Country = "Serbia",
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            ZipCode = "11000"
                        });
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("DefaultAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            BirthDate = new DateOnly(1980, 1, 1),
                            DefaultAddressId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b5"),
                            FirstName = "Stefan",
                            LastName = "Stefanov"
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            BirthDate = new DateOnly(2000, 5, 5),
                            DefaultAddressId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b6"),
                            FirstName = "Mara",
                            LastName = "Jakov"
                        });
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.CustomerArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("CustomerId", "ArticleId")
                        .IsUnique()
                        .HasFilter("\"OrderId\" IS NULL");

                    b.HasIndex("CustomerId", "ArticleId", "OrderId")
                        .IsUnique()
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.ToTable("CustomerArticle", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerArticle_Quantity", "\"Quantity\" >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b7"),
                            ArticleId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            ArticleName = "Philips Hue White and Color Ambiance A19 Smart LED Bulb",
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            Quantity = 3,
                            UnitPrice = 4999m
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b8"),
                            ArticleId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            ArticleName = "Ring Spotlight Cam",
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            Quantity = 1,
                            UnitPrice = 19999m
                        });
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.CustomerOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerOrder", (string)null);
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.Address", b =>
                {
                    b.HasOne("Matterway.Customers.Api.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.CustomerArticle", b =>
                {
                    b.HasOne("Matterway.Customers.Api.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matterway.Customers.Api.Domain.Entities.CustomerOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.CustomerOrder", b =>
                {
                    b.HasOne("Matterway.Customers.Api.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.CustomerOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
