// <auto-generated />
using System;
using Matterway.Customers.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matterway.Customers.Api.Migrations
{
    [DbContext(typeof(CustomersDb))]
    partial class CustomersDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("CustomerId", "ProductId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CartItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItem_Quantity", "\"Quantity\" >= 1");
                        });

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            ProductName = "Philips Hue White and Color Ambiance A19 Smart LED Bulb",
                            Quantity = 3,
                            UnitPrice = 4999m
                        },
                        new
                        {
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            ProductName = "Ring Spotlight Cam",
                            Quantity = 1,
                            UnitPrice = 19999m
                        });
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("DefaultAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            BirthDate = new DateOnly(1980, 1, 1),
                            FirstName = "Stefan",
                            LastName = "Stefanov",
                            SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3")
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            BirthDate = new DateOnly(2000, 5, 5),
                            FirstName = "Mara",
                            LastName = "Jakov",
                            SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4")
                        });
                });

            modelBuilder.Entity("Matterway.Customers.Api.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Matterway.Customers.Api.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
