// <auto-generated />
using System;
using Matterway.Customers.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Matterway.Customers.Api.Migrations
{
    [DbContext(typeof(CustomersDb))]
    partial class CustomersDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Matterway.Customers.Api.Features.CartItems.Domain.CartItem", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("CustomerId", "ProductId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            ProductId = new Guid("a301b154-9867-431f-a9c9-0328b2ce350f"),
                            ProductName = "Philips Hue White and Color Ambiance A19 Smart LED Bulb",
                            Quantity = 3,
                            UnitPrice = 4999.0
                        },
                        new
                        {
                            CustomerId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            ProductId = new Guid("853cb7f2-bd31-4627-9da5-17b32cc8c157"),
                            ProductName = "Ring Spotlight Cam",
                            Quantity = 1,
                            UnitPrice = 19999.0
                        });
                });

            modelBuilder.Entity("Matterway.Customers.Api.Features.Customers.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DefaultAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId")
                        .IsUnique();

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3"),
                            BirthDate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stefan",
                            LastName = "Stefanov",
                            SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b3")
                        },
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4"),
                            BirthDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mara",
                            LastName = "Jakov",
                            SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b4")
                        });
                });

            modelBuilder.Entity("Matterway.Customers.Api.Features.CartItems.Domain.CartItem", b =>
                {
                    b.HasOne("Matterway.Customers.Api.Features.Customers.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
