@startuml HLD: Class Diagram - Platform Overview
skinparam classAttributeIconSize 10
hide circle

' =======================
' MODULES
' =======================

package "Identity" {
  enum EIdentityRole {
    Admin
    Manager
    Customer
  }

  class SystemUser {
    +id: UUID
    --
    +userName: String
    +email: String
    +passwordHash: String
    +securityStamp: String
    +created: DateTime
  }

  class IdentityRole {
    +id: UUID
    --
    +name: String
    +normalizedName: String
  }

  class IdentityUserRole {
    +userId: UUID
    +roleId: UUID
  }

  class IdentityUserClaim {
    +id: Numeric
    --
    +userId: UUID
    ..
    +claimType: String
    +claimValue: String
  }

  SystemUser "1" -- "0..*" IdentityUserClaim
  SystemUser "1" -- "0..*" IdentityUserRole
  IdentityUserRole "0..*" -- "1" IdentityRole
}

package "Catalog" {
  class Discount {
    +code: String
    --
    +articleId: UUID
    ..
    +percentage: Numeric
    +validFrom: DateTime
    +validTo: DateTime?
  }

  class Article {
    +id: UUID
    --
    +articleCode: String
    +title: String
    +description: String
    +basePrice: Money
    +isAvailable: Boolean
    +createdAt: DateTime
    +updatedAt: DateTime
  }

  class ArticleDetailText {
    +articleId: UUID
    +detailSlug: String
    --
    +value: String
  }

  class ArticleDetailNumeric {
    +articleId: UUID
    +detailSlug: String
    --
    +value: Numeric
  }

  class Detail {
    +slug: String
    --
    +title: String
    +unit: String?
  }

  class ArticleImage {
    +id: UUID
    --
    +articleId: UUID
    ..
    +orderIndex: Numeric
    +imageUrl: String
    +imageAlt: String?
  }

  Discount "0..*" -- "1" Article : articleId
  ArticleDetailText "0..*" -- "1" Article : articleId
  ArticleDetailText "0..*" -- "1" Detail : detailSlug
  ArticleDetailNumeric "0..*" -- "1" Article : articleId
  ArticleDetailNumeric "0..*" -- "1" Detail : detailSlug
  ArticleImage "0..*" -- "1" Article : articleId
}

package "Customers" {
  class Address {
    +id: UUID
    --
    +customerId: UUID
    ..
    +country: String
    +city: String
    +zipCode: String
    +addressLine1: String
    +addressLine2: String
    +contactPhone: String
  }

  class Customer {
    +id: UUID
    --
    +firstName: String
    +lastName: String
    +birthDate: DateOnly
    +defaultAddressId: UUID?
  }

  class CustomerArticle {
    +id: UUID
    +articleId: UUID
    --
    +customerId: UUID
    +orderId: UUID?
    +articleName: String?
    +unitPrice: Money?
    +quantity: Numeric
  }

  class CustomerOrder {
    +orderId: UUID
    --
    +customerId: UUID
    ..
    +placedAt: DateTime
  }

  CustomerOrder "0..*" -- "1" Customer : customerId
  Customer "1" -- "0..1" Address : customerId
  CustomerArticle "0..*" -- "1" Customer : customerId
  CustomerArticle "0..*" -- "0..1" CustomerOrder : orderId
}

package "Sales" {

  class OrderDeliveryInfo {
    +id: UUID
    --
    +orderId: UUID
    ..
    +country: String
    +city: String
    +zipCode: String
    +addressLine1: String
    +addressLine2: String
    +contactPhone: String
  }
  class Order {
    +id: UUID
    --
    +customerId: UUID?
    ..
    +placedAt: DateTime
    +type: EOrderType
  }

  class OrderItem {
    +id: UUID
    --
    +orderId: UUID
    ..
    +articleId: UUID
    +articleTitle: String
    +unitPrice: Money
    +quantity: Numeric
  }

  note right of Order
    Flow (happy path)
    Customer -> Sales: Place order
    Sales -> Inventory: Request stock reservation
    Inventory -> Sales: StockReserved
    Sales: Initiate/Authorize payment
    Sales: PaymentCaptured
    Sales -> Inventory: Fulfillment request
    Inventory -> Sales: OrderDeliveryInfoFulfilled
  end note

  enum EOrderType {
    Retail
    Ecommerce
  }

  enum EOrderStatusType {
    Processing
    Reserved
    Delivery
    Completed
    Cancelled
  }

  class OrderStatus {
    +id: Numeric
    --
    +orderId: UUID
    ..
    +changedAt: DateTime
    +status: EOrderStatusType
    +note: String?
  }

  class Payment {
    +id: UUID
    --
    +orderId: UUID
    ..
    +provider: String
    +referenceId: String
    +amount: Money
    +status: EPaymentStatus
    +createdAt: DateTime
  }

  enum EPaymentStatus {
    Reserved
    Charged
    Failed
    Refunded
  }

  OrderItem "0..*" -- "1" Order : orderId
  OrderStatus "0..*" -- "1" Order : orderId
  OrderDeliveryInfo "1" -- "1" Order : OrderId
  Payment "0..*" -- "1" Order : orderId
}

' =======================
' RELATIONSHIPS
' =======================

' Identity
SystemUser "1" .up. "0..1" Customer

' Customers
CustomerArticle "0..*" .. "1" Article
CustomerOrder "0..1" .. "1" Order
@enduml
