@startuml SUCatalogUseCaseDiagram
title SU: Catalog - Use Case Diagram
left to right direction
skinparam shadowing false
skinparam actorStyle hollow

actor :Anonymous: as anon
actor :Customer: as csmr
anon <-- csmr

rectangle #line:transparent {
  actor :Employee: as empl
  actor :Manager: as mngr
  actor :Operator: as oprt
}
oprt --> empl
mngr --> empl

package "Catalog API" {
  usecase "View Article Data" as viewArticleData
  usecase "View Discounts" as viewDiscounts
  usecase "Browse Articles" as browseArticles
  browseArticles <.. viewArticleData: <<extend>>
  browseArticles <.. viewDiscounts: <<include>>

  usecase "Administer Articles" as administerArticles
  usecase "Administer Article Details" as administerArticleDetails
  usecase "Administer Article Images" as administerArticleImages
  usecase "Administer Discounts" as administerDiscounts
  administerArticleDetails ..> administerArticles : <<include>>
  administerArticleImages ..> administerArticles : <<include>>

  usecase "View Details" as viewDetails
  usecase "Administer Details" as administerDetails
  viewDetails <.. administerDetails : <<include>>

  usecase "Import Catalog Archive" as importCatalogArchive
  usecase "Export Catalog Archive" as exportCatalogArchive
}

anon --- browseArticles
anon --- viewDetails

administerArticles -- oprt
administerDiscounts -- oprt
administerDetails -- oprt
importCatalogArchive -- mngr
exportCatalogArchive -- mngr
@enduml
