@startuml SUIdentityUseCaseDiagram
title SU: Identity - Use Case Diagram
left to right direction
skinparam shadowing false
skinparam actorStyle hollow

actor user as "User"

rectangle #line:transparent {
  actor empl as "Employee"
  actor sysm as "System"
}

user --|> empl

package "Identity" {
  usecase signIn as "Sign In"
  usecase refreshSession as "Refresh Session"
  usecase signOut as "Sign Out"

  usecase manageSystemUsers as "Manage System Users
                                ..<i>extention points</i>..
                                Delete System User [manager only]"
  usecase deleteSystemUser as "Delete System User"
  usecase viewSystemUsers as "View System Users"

  usecase viewUserPermissions as "View User Permissions"
  usecase manageUserPermissions as "Manage User Permissions"

  usecase createEmployeeAccount as "Create Employee User Account"
  usecase createCustomerAccount as "Create Customer User Account"
  usecase introspectAccessToken as "Introspect Access Token"

  manageSystemUsers .up.> viewSystemUsers : <<include>>
  manageUserPermissions .up.> viewSystemUsers : <<include>>
  deleteSystemUser .up.> manageSystemUsers : <<extend>>
}

user --- signIn
user --- refreshSession
user --- signOut

manageSystemUsers --- empl : perm:[operator,manager]
viewUserPermissions --- empl : perm:[operator,manager]
manageUserPermissions --- empl : perm:[manager]
createEmployeeAccount --- empl : perm:[manager]

introspectAccessToken --- sysm
createCustomerAccount --- sysm
@enduml
