// <auto-generated />
using System;
using Identity.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.API.Migrations;

[DbContext(typeof(IdentityDbContext))]
[Migration("20230409144534_Initialize")]
partial class Initialize
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Identity.API.Entities.Session", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("Created")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("Expires")
                    .IsRequired()
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("RefreshExpires")
                    .IsRequired()
                    .HasColumnType("datetime2");

                b.Property<string>("RefreshToken")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("SystemUserId")
                    .IsRequired()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("SystemUserId");

                b.ToTable("Session");

                b.HasData(
                    new
                    {
                        Id = new Guid("4e54e945-90e7-4f75-88f7-9d9b84d7c81c"),
                        Created = new DateTime(2023, 4, 9, 14, 45, 34, 255, DateTimeKind.Utc).AddTicks(148),
                        Expires = new DateTime(2023, 4, 9, 15, 0, 34, 255, DateTimeKind.Utc).AddTicks(155),
                        RefreshExpires = new DateTime(2023, 4, 21, 14, 45, 34, 255, DateTimeKind.Utc).AddTicks(1429),
                        RefreshToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2ODEwNTE1MzQsImV4cCI6MTY4MjA4ODMzNCwiaWF0IjoxNjgxMDUxNTM0fQ.e0D9bDzl9sAEQz3TQATve0nw1EMws8Th0ckaTllI1iw",
                        SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                        Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2ODEwNTE1MzQsImV4cCI6MTY4MTA1MjQzNCwiaWF0IjoxNjgxMDUxNTM0fQ.HEXgC9ASwkSSw4YVZcMofOAlfUBksTYsqqzNwMg_ErI"
                    });
            });

        modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Role")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("SystemUser");

                b.HasData(
                    new
                    {
                        Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                        Created = new DateTime(2023, 4, 9, 14, 45, 34, 196, DateTimeKind.Utc).AddTicks(5824),
                        Email = "user@example.com",
                        PasswordHash = "AQAAAAIAAYagAAAAEJBEDW/C40/poCE8DcuYtfzOq14nUh6lGAE0Ml9B1ceWh3OP+k7hh++rxx5zGbDyKw==",
                        Role = 0
                    });
            });

        modelBuilder.Entity("Identity.API.Entities.Session", b =>
            {
                b.HasOne("Identity.API.Entities.SystemUser", "SystemUser")
                    .WithMany("Sessions")
                    .HasForeignKey("SystemUserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("SystemUser");
            });

        modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
            {
                b.Navigation("Sessions");
            });
#pragma warning restore 612, 618
    }
}
