// <auto-generated />
using System;
using Identity.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.API.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20230331131816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.API.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expires")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RefreshExpires")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SystemUserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Session");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e54e945-90e7-4f75-88f7-9d9b84d7c81c"),
                            Created = new DateTime(2023, 3, 31, 13, 18, 16, 104, DateTimeKind.Utc).AddTicks(781),
                            Expires = new DateTime(2023, 3, 31, 13, 33, 16, 104, DateTimeKind.Utc).AddTicks(788),
                            RefreshExpires = new DateTime(2023, 4, 12, 13, 18, 16, 104, DateTimeKind.Utc).AddTicks(2241),
                            RefreshToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQ3VzdG9tZXIiLCJuYmYiOjE2ODAyNjg2OTYsImV4cCI6MTY4MTMwNTQ5NiwiaWF0IjoxNjgwMjY4Njk2fQ.gIqBOvqHYkW9AQ6Hfrob6GhhSQbnI4AP_udGVcb977o",
                            SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQ3VzdG9tZXIiLCJuYmYiOjE2ODAyNjg2OTYsImV4cCI6MTY4MDI2OTU5NiwiaWF0IjoxNjgwMjY4Njk2fQ.lzK7qD6vKVIUXe9Ut1Lb4grHN_UqqfuBqtdlWzGQCVM"
                        });
                });

            modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Created = new DateTime(2023, 3, 31, 13, 18, 16, 39, DateTimeKind.Utc).AddTicks(1151),
                            Email = "user@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEPJ7tY6J1UfLmM4vRQ3zg2wrKHnmhiJ5BoDogxS63HI7Nx916b+lp6m/setlZrTSYA==",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Identity.API.Entities.Session", b =>
                {
                    b.HasOne("Identity.API.Entities.SystemUser", "SystemUser")
                        .WithMany("Sessions")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
