// <auto-generated />
using System;
using Identity.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.API.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20230409024811_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.API.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expires")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RefreshExpires")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SystemUserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Session");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e54e945-90e7-4f75-88f7-9d9b84d7c81c"),
                            Created = new DateTime(2023, 4, 9, 2, 48, 11, 328, DateTimeKind.Utc).AddTicks(5286),
                            Expires = new DateTime(2023, 4, 9, 3, 3, 11, 328, DateTimeKind.Utc).AddTicks(5290),
                            RefreshExpires = new DateTime(2023, 4, 21, 2, 48, 11, 328, DateTimeKind.Utc).AddTicks(6502),
                            RefreshToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2ODEwMDg0OTEsImV4cCI6MTY4MjA0NTI5MSwiaWF0IjoxNjgxMDA4NDkxfQ.aFmfTCgqzuirTUDNNLLH_LfI4gAhATPRrenF9zQtAaY",
                            SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2ODEwMDg0OTEsImV4cCI6MTY4MTAwOTM5MSwiaWF0IjoxNjgxMDA4NDkxfQ.a3T2WSCmFRzEZ4-WZ7yWo1s6kOjdvUQbpGa0dYU0VLM"
                        });
                });

            modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Created = new DateTime(2023, 4, 9, 2, 48, 11, 272, DateTimeKind.Utc).AddTicks(7341),
                            Email = "user@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENpALCvs+2eF8D3WNtiCky5pLNgQaonBmUxiNKbuqOudWb3VS8wQVbXpcBvs5cTS2w==",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Identity.API.Entities.Session", b =>
                {
                    b.HasOne("Identity.API.Entities.SystemUser", "SystemUser")
                        .WithMany("Sessions")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
