// <auto-generated />
using System;
using Identity.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.API.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.API.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expires")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RefreshExpires")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SystemUserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Session");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e54e945-90e7-4f75-88f7-9d9b84d7c81c"),
                            Created = new DateTime(2023, 4, 9, 5, 11, 27, 6, DateTimeKind.Utc).AddTicks(7415),
                            Expires = new DateTime(2023, 4, 9, 5, 26, 27, 6, DateTimeKind.Utc).AddTicks(7423),
                            RefreshExpires = new DateTime(2023, 4, 21, 5, 11, 27, 6, DateTimeKind.Utc).AddTicks(8484),
                            RefreshToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2ODEwMTcwODcsImV4cCI6MTY4MjA1Mzg4NywiaWF0IjoxNjgxMDE3MDg3fQ.H0f9xFiXcbkU4vT1lEmpMurQ5TzBbNr-0v9o5RzN78A",
                            SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2ODEwMTcwODcsImV4cCI6MTY4MTAxNzk4NywiaWF0IjoxNjgxMDE3MDg3fQ.b5gPuP6-Xsfd8XTJ91agFjP6LKPgDx5iBC0abWzIpcU"
                        });
                });

            modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Created = new DateTime(2023, 4, 9, 5, 11, 26, 950, DateTimeKind.Utc).AddTicks(3524),
                            Email = "user@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEDVImPQgm5pkjVhU5APZgNN4+opiXDMrORy9hgbN9IQKxAy6xV2GqYrgdQjNwUr2Ww==",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Identity.API.Entities.Session", b =>
                {
                    b.HasOne("Identity.API.Entities.SystemUser", "SystemUser")
                        .WithMany("Sessions")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
