// <auto-generated />
using System;
using Identity.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.API.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.API.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expires")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SystemUserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId")
                        .IsUnique();

                    b.ToTable("Session");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e54e945-90e7-4f75-88f7-9d9b84d7c81c"),
                            Created = new DateTime(2023, 3, 29, 9, 41, 32, 975, DateTimeKind.Utc).AddTicks(6917),
                            Expires = new DateTime(2023, 3, 29, 9, 56, 32, 975, DateTimeKind.Utc).AddTicks(6923),
                            RefreshToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQ3VzdG9tZXIiLCJuYmYiOjE2ODAwODI4OTIsImV4cCI6MTY4MTExOTY5MiwiaWF0IjoxNjgwMDgyODkyfQ.D6iAtYDSHJcKj7tCYagUdfbuKr8a5MtUbIesG3vw_NY",
                            SystemUserId = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOWQ2NGI2NC05M2MxLTQxYTgtYTc0Mi04YThiYTgxZTIwYjEiLCJyb2xlIjoiQ3VzdG9tZXIiLCJuYmYiOjE2ODAwODI4OTIsImV4cCI6MTY4MDA4Mzc5MiwiaWF0IjoxNjgwMDgyODkyfQ.UgNnaWV7wCAo1NpSB8UWZScmWSFkEAEIk_ZtOx2-D0c"
                        });
                });

            modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9d64b64-93c1-41a8-a742-8a8ba81e20b1"),
                            Created = new DateTime(2023, 3, 29, 9, 41, 32, 913, DateTimeKind.Utc).AddTicks(5893),
                            Email = "user@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAELjuk8E9UXQ7uK9JUG8aMOpbzNbkg1UXa4iLQSl/DAqkxaC4jnQkJfD4qNuRvSkWfA==",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Identity.API.Entities.Session", b =>
                {
                    b.HasOne("Identity.API.Entities.SystemUser", "SystemUser")
                        .WithOne("Session")
                        .HasForeignKey("Identity.API.Entities.Session", "SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Identity.API.Entities.SystemUser", b =>
                {
                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
}
